# Docker Compose file Reference (https://docs.docker.com/compose/compose-file/)
version: "3.9"

services:
  customer-service-app:
    container_name: lorincetawamba/onlineshop-customer-service
    restart: always
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - 8081:8081
    environment:
      - PGUSER=dev
      - PGPASSWORD=dev
      - PGDATABASE=bd_customer_service # NOM DE LA BD
      - PGHOST=postgre-db-data # NAME OF THE SERVICE
    depends_on:
      - postgre-db-data

  postgre-db-data:
    image: postgres:14-alpine
    container_name: lorincetawamba/onlineshop-customer-bd
    restart: always
    environment:
      POSTGRES_DB: bd_customer_service
      POSTGRES_USER: dev
      POSTGRES_PASSWORD: dev
      PGDATA: /var/lib/postgresql/data
    ports:
      - "5432:5432"
    volumes:
      - postgre-db-data:/var/lib/postgresql/data

  pgadmin:
    container_name: lorincetawamba/pgadmin4_container
    image: dpage/pgadmin4:5.5
    restart: always
    environment:
      PGADMIN_DEFAULT_EMAIL: admin@admin.com
      PGADMIN_DEFAULT_PASSWORD: dev
      PGADMIN_LISTEN_PORT: 80
    ports:
      - "8080:80"
    volumes:
      - pgadmin-data:/var/lib/pgadmin

volumes:
  postgre-db-data:
  pgadmin-data: